# Generated by Django 5.1.1 on 2024-10-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthprediction', '0002_chatgptquery'),
    ]

    operations = [
        migrations.CreateModel(
            name='EyeDiseasePredict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eye_disease_image', models.ImageField(upload_to='eye_disease_images')),
            ],
        ),
    ]
