# Generated by Django 5.1.1 on 2024-10-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthprediction', '0003_eyediseasepredict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eyediseasepredict',
            name='eye_disease_image',
            field=models.ImageField(upload_to='eye_disease_images/'),
        ),
    ]
